# Generated by Django 2.1.1 on 2019-01-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uv_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv_date', models.DateTimeField(verbose_name='datetime of reading')),
                ('uv', models.DecimalField(decimal_places=6, max_digits=8)),
                ('sun_alt', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
    ]
