# Generated by Django 2.1.1 on 2019-01-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasppi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uv_data',
            new_name='openUVData',
        ),
    ]
