# Generated by Django 2.1.1 on 2019-01-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasppi', '0002_auto_20190129_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='darkSkyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv_date', models.DateTimeField(verbose_name='datetime of reading')),
                ('uv', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
    ]
