# Generated by Django 2.1.1 on 2019-02-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasppi', '0003_darkskydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilyWeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv_date', models.DateTimeField(verbose_name='datetime of reading')),
                ('uv', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='darkSkyData',
        ),
        migrations.RemoveField(
            model_name='openuvdata',
            name='sun_alt',
        ),
    ]
